[package]
name = "secp256k1_signature_program"
version = "0.1.0"
edition = "2021"
[dependencies]
arch_program = "0.5.5"
borsh = { version = "1.5.1", features = ["derive"] }
libsecp256k1 = { version = "0.7.0", default-features = false }
[lib]
crate-type = ["cdylib", "lib"]
[workspace]