[package]
name = "vote-example"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_sdk = "0.5.1"
arch_program = "0.5.1"
arch_test_sdk = "0.5.1"
hex = "0.4.3"
bincode = "1.3.3"
libp2p = { workspace = true}

[dev-dependencies]
serial_test = "3.1.1"

[lib]
path = "src/lib.rs"