[package]
name = "balance_inflation_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_program = "0.5.3"
borsh = { version = "1.5.1", features = ["derive"] }

[lib]
crate-type = ["cdylib", "lib"]

[workspace]