[package]
name = "cpi_disable_cpi_program"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_program = "0.5.6"
borsh = { version = "1.5.1", features = ["derive"] }

[lib]
crate-type = ["cdylib", "lib"]

[workspace] 