[package]
name = "fungible-token-standard"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
arch_program = "0.1.0"
borsh = "1.5.3"
hex = "0.4.3"
arch_sdk = "0.1.0"
bitcoin = { version = "0.32.3", features = ["serde"] }
rand = "0.8.5"
