[package]
name = "unbalanced_cpi_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_program = "0.5.2"
borsh = { version = "1.5.1", features = ["derive"] }

[lib]
crate-type = ["cdylib", "lib"]

[workspace]