[package]
name = "escrow"
version.workspace = true
edition = "2021"

[dependencies]
arch_sdk = "0.11.0"
arch_program = "0.11.0"
apl-token = { path = "../../token", features = ["no-entrypoint"] }
apl-associated-token-account = { path = "../../associated-token-account", features = [
    "no-entrypoint",
] }


borsh = { version = "1.4.0", features = ["derive"] }
bitcoin = { version = "0.32.3", features = ["serde", "rand"] }
[dev-dependencies]

[lib]
path = "src/lib.rs"
