[workspace]
[package]
name = "create-new-account-program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5.3" }
arch_program = "0.3.2"

[lib]
crate-type = ["cdylib", "lib"]
