[workspace]
[package]
name = "create-new-account-program"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_program = { path = "../../../program" }
borsh = { version = "1.5.3" }

[lib]
crate-type = ["cdylib", "lib"]
