[package]
name = "keccak256-hash"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_sdk = "0.5.8"
arch_program = "0.5.8"
borsh = { version = "1.4.0", features = ["derive"] }
hex = "0.4.3"
sha3 = "0.10"

[dev-dependencies]

[lib]
path = "src/lib.rs" 